#!/usr/bin/perl  -w 

## diffit  list D2   Like diffch $R .

($L1, $D2) = @ARGV ;
if (!(defined $D2))  {  
 printf "usage: diffch sourcedir destdir\n" ;
 exit 0 ;
}

open (I1, $L1) || die "badly\n" ; 

foreach  $line (<I1>)  { 
 ($ff) = split " ", $line ; 
 next unless (defined $ff) ; 
 next if ($ff =~ /\#/) ; 
 next unless (-r "$D2/$ff") ;
  system "diff $ff $D2" ;
  print "$ff diffed\n" ;
}
